from typing import List

from dawe_nrm.schemas import LUTSchema

endpoints: List[LUTSchema] = [
    LUTSchema(
        endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-fauna-age-classes",
        label="Age classes",
        description="Refers to a collection of fauna age class or growth stage, i.e., whether the fauna under study is a juvenile, adult, nymph, metamorph, immature, tadpole, or in some cases even an egg.",
        collection_url="https://linked.data.gov.au/def/nrm/0e2641c3-0d7e-4d94-8cd7-02c21d564630",
        uuid_namespace="age class",
    ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-fauna-behaviours",
    #     label="Animal behaviour codes",
    #     description="A collection of animal behaviour types and its codes.",
    #     collection_uuid="1301857c-4e02-4000-966b-a0d0ce60368f",
    #     uuid_namespace="animal behaviour",
    # ),
    LUTSchema(
        endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-fauna-pouch-conditions",
        label="Animal pouch conditions",
        description="Refers to the condition of pouch of an animal (such as marsupials), i.e., whether the pouch is developed, or Not, and if there are any young ones.",
        collection_url="https://linked.data.gov.au/def/nrm/4fab0c1c-c127-474e-8f5e-4afe45fec0ed",
        uuid_namespace="animal pouch condition",
    ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-fauna-sexes",
    #     label="Animal sex codes",
    #     description="A collection of animal sex types and its codes.",
    #     collection_uuid="fcc3a1e1-3e35-4a4f-bd44-eface035025c",
    #     uuid_namespace="animal sex",
    # ),
    LUTSchema(
        endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-fauna-teats-conditions",
        label="Female teat conditions",
        description="A collection of animal teats condition types, such as lactating, distended or button.",
        collection_url="https://linked.data.gov.au/def/nrm/d2665d51-db1d-48ad-a80d-48593d280b76",
        uuid_namespace="animal teats condition",
    ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-fauna-testes-conditions",
    #     label="Animal testes condition codes",
    #     description="A collection of animal testes condition types and its codes.",
    #     collection_uuid="c5d3877d-1a83-4a87-9bdd-05f77c516df6",
    #     uuid_namespace="animal testes condition",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-basal-dbh-instruments",
    #     label="DBH instruments types codes",
    #     description="A collection of DBH instruments type and its codes.",
    #     collection_uuid="b18974ea-7395-4c14-9d9f-3c1fa6b2c8a9",
    #     uuid_namespace="basal dbh instruments",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-basal-area-factors",
    #     label="Basal area factors codes",
    #     description="A collection of basal area factors and its codes.",
    #     collection_uuid="13d010d7-91b7-4621-b80a-70cb4324ddf5",
    #     uuid_namespace="basal area factors",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-basal-sweep-sampling-points",
    #     label="Basal sweep sampling points codes",
    #     description="A collection of basal sweep sampling points and its codes.",
    #     collection_uuid="96d41885-70e5-44c1-bafc-73027f47941b",
    #     uuid_namespace="basal sweep sampling points",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-basal-tree-trunk-types",
    #     label="Basal tree trunk types",
    #     description="A collection of basal tree trunk types and its codes.",
    #     collection_uuid="9282400b-56c3-49a9-bb82-87ef74914690",
    #     uuid_namespace="basal tree trunk",
    # ),
    LUTSchema(
        endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-fauna-breeding-codes",
        label="Breeding statuses",
        description="Refers to a collection of reproductive status of a fauna individual. For example, in female mammals, whether the mammal is pregnant or not, or is with a dependent young; in female frogs and reptiles, whether the female is gravid (fertile), or non-gravid; in male frogs, whether the vocal sac is obvious, nuptial pads inconspicuous, nuptial pads obvious but not fully developed, nuptial pads fully developed, or in amplexus.",
        collection_url="https://linked.data.gov.au/def/nrm/b7dc10d2-c0aa-46b3-94da-685cd0a723e4",
        uuid_namespace="breeding status",
    ),
    LUTSchema(
        endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-rumps",
        label="Clinical scoring - rump",
        description="A collection of clinical condition scores (0 - 7) of a mammalian rump (e.g., Koala), with '0' referred to 'normal condition' and '7' being 'progressive decline or myiasis'.",
        collection_url="https://linked.data.gov.au/def/nrm/8799d474-09eb-5112-aa9d-87710cd1661c",
        uuid_namespace="rump",
    ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-camera-battery-types",
    #     label="Camera battery types codes",
    #     description="A collection of camera battery types and its codes.",
    #     collection_uuid="43b3b0bd-8de4-4cba-88b5-c7c094fa5de5",
    #     uuid_namespace="camera battery types",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-camera-lure-types",
    #     label="Camera lure types codes",
    #     description="A collection of camera lure types and its codes.",
    #     collection_uuid="32f45f74-6d73-416c-9551-1ade13616bd2",
    #     uuid_namespace="camera lure types",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-camera-lure-varieties",
    #     label="Camera lure varieties codes",
    #     description="A collection of camera lure varieties and its codes.",
    #     collection_uuid="313428d7-9dd7-4bb5-9ba1-1de6339589ff",
    #     uuid_namespace="camera lure varieties",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-camera-media-types",
    #     label="Camera media types codes",
    #     description="A collection of camera media types and its codes.",
    #     collection_uuid="e3097ab4-6299-41a2-9475-bfa961a5ea57",
    #     uuid_namespace="camera media types",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-camera-night-modes",
    #     label="Camera night modes codes",
    #     description="A collection of camera night modes and its codes.",
    #     collection_uuid="ba07ad76-df50-4b40-b915-65eaaf811104",
    #     uuid_namespace="camera night modes",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-camera-operational-statuses",
    #     label="Camera operational statuses codes",
    #     description="A collection of camera operational statuses and its codes.",
    #     collection_uuid="9ef53244-7dff-408c-bf87-3468b42cc132",
    #     uuid_namespace="camera operational statuses",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-camera-picture-intervals",
    #     label="Camera picture intervals codes",
    #     description="A collection of camera picture intervals and its codes.",
    #     collection_uuid="3c2c9b30-d44f-4d50-8276-4f40b5870584",
    #     uuid_namespace="camera picture intervals",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-camera-sensor-sensitivities",
    #     label="Camera sensor sensitivities codes",
    #     description="A collection of camera sensor sensitivities and its codes.",
    #     collection_uuid="3790f4af-6123-4c61-8440-3d164bda7238",
    #     uuid_namespace="camera sensor sensitivities",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-camera-trap-mounts",
    #     label="Camera trap mounts codes",
    #     description="A collection of camera trap mounts and its codes.",
    #     collection_uuid="0c364c83-f031-477b-88ae-9c438c84e175",
    #     uuid_namespace="camera trap mounts",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-camera-trap-points",
    #     label="Camera trap points codes",
    #     description="A collection of camera trap points and its codes.",
    #     collection_uuid="2742ccd6-cbe7-406c-a4aa-265944774454",
    #     uuid_namespace="camera trap points",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-climatic-conditions",
    #     label="Climatic condition codes",
    #     description="A collection of climatic condition types and its codes.",
    #     collection_uuid="2ebfee89-92db-44b3-bb89-06dd92798ae6",
    #     uuid_namespace="climatic condition",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-cwd-decay-classes",
    #     label="Coarse Woody Debris decay classes codes",
    #     description="A collection of Coarse Woody Debris decay classes and "
    #     "its codes.",
    #     collection_uuid="b5180d8a-75b6-4bca-9413-0e507e910387",
    #     uuid_namespace="coarse woody debris decay classes",
    # ),
    LUTSchema(
        endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-plot-dimensions",
        label="plot dimensions",
        description="The plot dimensions used for  ecological surveys. A standard protocol uses 100 x 100 m (1 hectare) and a sub-plot uses 40 x 40 m.",
        collection_url="https://linked.data.gov.au/def/nrm/05c7a145-a675-4753-88d1-d86fa19dac3b",
        uuid_namespace="coarse woody debris plot dimensions",
    ),
    LUTSchema(
        endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-plot-types",
        label="plot types",
        description="A collection of plot types used either for standard ecological monitoring, or for experimental sampling design. Plot types are assigned depending on their intended use in before-after-control-impact (BACI) assessments. For instance, plots are categorized as an 'Impact' type if they serve in experimental sampling designs, or as 'Control' type if they remain undisturbed and solely used for natural observations.",
        collection_url="https://linked.data.gov.au/def/nrm/beaa6b82-a4ea-5e4d-a354-de3f5394bc6b",
        uuid_namespace="plot types",
    ),
    LUTSchema(
        endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-plot-nearest-infrastructures",
        label="Intensive uses",
        description="This class includes land uses that involve high levels of interference with natural processes, generally in association with closer settlement. The level of intervention may be high enough to completely remodel the natural landscape—the vegetation, surface and groundwater systems, and the land surface. If crop and or animal type is known, record this in the commodity field.",
        collection_url="http://www.neii.gov.au/def/voc/ACLUMP/australian-land-use-and-management-classification/Intensive-uses",
        uuid_namespace="intensive uses",
    ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-bioregions",
    #     label="Interim Biogeographic Regionalisation for Australia (IBRA7) Codes",
    #     description="This vocabulary contains the region and subregion codes for the IBRA7.",
    #     collection_uuid="http://linked.data.gov.au/dataset/bioregion/IBRA7",
    #     uuid_namespace="bioregions",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-cwd-sampling-survey-methods",
    #     label="Coarse Woody Debris sampling survey methods codes",
    #     description="A collection of Coarse Woody Debris sampling survey "
    #     "methods and its codes.",
    #     collection_uuid="bd41602d-36df-435c-870c-496dfd523ec1",
    #     uuid_namespace="coarse woody debris sampling survey methods",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-cwd-transect-numbers",
    #     label="Coarse Woody Debris transect numbers codes",
    #     description="A collection of Coarse Woody Debris transect numbers "
    #     "and its codes.",
    #     collection_uuid="c117bd06-9603-400d-a20d-29f56ffa78cc",
    #     uuid_namespace="coarse woody debris transect numbers",
    # ),
    LUTSchema(
        endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-directions",
        label="Direction codes",
        description="A collection of direction codes.",
        collection_url="https://linked.data.gov.au/def/nrm/232d5fdd-c15f-4a84-865e-46ea20b82ff1",
        uuid_namespace="coarse woody debris transect orientations",
    ),
    LUTSchema(
        endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-condition-life-stages",
        label="Life stages",
        description="A collection of various life stages of a plant individual. Examples include, budding, vegetative, seedling, sapling, flowering, fruiting, mature, senescent and recently shed.",
        collection_url="https://linked.data.gov.au/def/nrm/5f82c583-167b-4ed2-b25e-4d67decb3f2d",
        uuid_namespace="condition life stages",
    ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-condition-vegetation-diameter-classes",
    #     label="Condition vegetation diameter classes codes",
    #     description="A collection of condition vegetation diameter classes "
    #     "and its codes.",
    #     collection_uuid="fe0b8990-dc4c-4fc7-85e8-be08da5721a0",
    #     uuid_namespace="condition vegetation diameter classes",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-condition-vertebrate-pest-presence-evidences",
    #     label="Condition vertebrate pest presence evidences codes",
    #     description="A collection of condition vertebrate pest presence "
    #     "evidences and its codes.",
    #     collection_uuid="69638c57-1c38-47e1-8bae-c821411c3a30",
    #     uuid_namespace="condition vertebrate pest presence evidences",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-condition-vertebrate-pest-types",
    #     label="Condition vertebrate pest types codes",
    #     description="A collection of condition vertebrate pest types and its codes.",
    #     collection_uuid="579449ad-4cea-4272-afa3-67f207941fb1",
    #     uuid_namespace="condition vertebrate pest types",
    # ),
    LUTSchema(
        endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-corners",
        label="plot marker locations",
        description="A collection of spatial points representing locations within the plot, such as, northeast, northwest, southeast, southwest and centre.",
        collection_url="https://linked.data.gov.au/def/nrm/21072cd8-f8df-42ad-a3b0-c7adee21bc6d",
        uuid_namespace="corners",
    ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-cover-codes",
    #     label="Cover class codes",
    #     description="A collection of cover class types and its codes.",
    #     collection_uuid="6aaa330c-3d60-419b-a29b-a2dbc6d67928",
    #     uuid_namespace="cover class",
    # ),
    LUTSchema(
        endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-disturbances",
        label="disturbance types",
        description="A collection of land surface disturbance types describing the historical land-use, such as 'cultivated land', 'rain-fed', 'clearing', 'grazing', 'extensive clearing', etc.",
        collection_url="https://linked.data.gov.au/def/nrm/f5a470e8-d29f-4ff6-b50d-529b0444dbe4",
        uuid_namespace="disturbance type",
    ),
    LUTSchema(
        endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-exact-or-estimates",
        label="Measured quantity types",
        description="Refers to the count of an invertebrate specimens, i.e., whether the quantity is an exact match or an estimate of the total number of individuals.",
        collection_url="https://linked.data.gov.au/def/nrm/12750b20-0e91-4878-9029-b4d9d7788429",
        uuid_namespace="exact or estimates",
    ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-fauna-bird-activity-types",
    #     label="Fauna bird activity types codes",
    #     description="A collection of fauna bird activity types and its codes.",
    #     collection_uuid="c7a51f30-97e8-4232-b1f3-a248d58f1a60",
    #     uuid_namespace="fauna bird activity types",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-fauna-bird-breeding-types",
    #     label="Fauna bird breeding types codes",
    #     description="A collection of fauna bird breeding types and its codes.",
    #     collection_uuid="028f570d-0cf0-4e94-b288-ac8d852f2230",
    #     uuid_namespace="fauna bird breeding types",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-fauna-bird-observation-location-types",
    #     label="Fauna bird observation location types codes",
    #     description="A collection of fauna bird observation location types "
    #     "and its codes.",
    #     collection_uuid="2f0470aa-2c05-4e87-a5ac-1d50205b9927",
    #     uuid_namespace="fauna bird observation location types",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-fauna-bird-observation-types",
    #     label="Fauna bird observation types codes",
    #     description="A collection of fauna bird observation types and its codes.",
    #     collection_uuid="035dd68f-d3ae-43a0-89bb-5a4e60b40969",
    #     uuid_namespace="fauna bird observation types",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-fauna-bird-survey-types",
    #     label="Fauna bird survey types codes",
    #     description="A collection of fauna bird survey types and its codes.",
    #     collection_uuid="6a3381c8-20c7-4c8b-a078-649254d43b0f",
    #     uuid_namespace="fauna bird survey types",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-fauna-maturities",
    #     label="Fauna maturities codes",
    #     description="A collection of fauna maturities and its codes.",
    #     collection_uuid="a01656de-9627-4067-ad09-269242badbcb",
    #     uuid_namespace="fauna maturities",
    # ),
    LUTSchema(
        endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-voucher-conditions",
        label="Fauna specimen conditions",
        description="Refers to the condition of fauna voucher specimen. The conditions can range for example, from a 'fresh (estimate <24 hours)' to 'partially degenerated (estimate 2-7 days)' to almost 'long dead (>4 weeks)'.",
        collection_url="https://linked.data.gov.au/def/nrm/f0647b85-a014-4299-b23f-6aeb25e834bc",
        uuid_namespace="fauna specimen conditions",
    ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-fauna-trap-disturbeds",
    #     label="Fauna trap disturbeds codes",
    #     description="A collection of fauna trap disturbeds and its codes.",
    #     collection_uuid="45eb0e0f-be9f-4384-9d95-47f51ccec94c",
    #     uuid_namespace="fauna trap disturbeds",
    # ),
    LUTSchema(
        endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-fire-histories",
        label="Fire history types",
        description="Refers to the site-level fire event history, i.e., whether the site has been burnt recently or in the past, or unburnt.",
        collection_url="https://linked.data.gov.au/def/nrm/6e9d2f51-ce64-4c67-8391-d14a8bf96b6b",
        uuid_namespace="fire history",
    ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-fire-in-canopy-sky-statuses",
    #     label="Fire in-canopy-sky statuses codes",
    #     description="A collection of fire in-canopy-sky statuses and its codes.",
    #     collection_uuid="15a03c34-142b-469c-9ec5-0d516fd6c1e7",
    #     uuid_namespace="fire in-canopy-sky statuses",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-fire-plot-burned-statuses",
    #     label="Fire plot burned statuses codes",
    #     description="A collection of fire plot burned statuses and its codes.",
    #     collection_uuid="5662a7dd-c1da-4659-8290-a1e6e42c879f",
    #     uuid_namespace="fire plot burned statuses",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-fire-regeneration-statuses",
    #     label="Fire regeneration statuses codes",
    #     description="A collection of fire regeneration statuses and its codes.",
    #     collection_uuid="a1b8fc00-5d5f-40f8-a7e1-0b09d4bbba4b",
    #     uuid_namespace="fire regeneration statuses",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-fire-substrate-types",
    #     label="Fire substrate codes",
    #     description="A collection of fire substrate types and its codes.",
    #     collection_uuid="c7a0692c-113c-4593-ae04-5e49aba70fdf",
    #     uuid_namespace="fire substrate",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-flora-voucher-types",
    #     label="Flora voucher types codes",
    #     description="A collection of flora voucher types and its codes.",
    #     collection_uuid="463ec6ac-c3cf-4a9f-8a5d-f9ce38c3c405",
    #     uuid_namespace="flora voucher types",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-habitats",
    #     label="Habitat description codes",
    #     description="A collection of habitat description types and its codes.",
    #     collection_uuid="c19a0098-1f3f-4bc2-b84d-fdb6d4e24d6f",
    #     uuid_namespace="habitat description",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-invertebrate-active-sampling-capture-equipments",
    #     label="Invertebrate active sampling capture equipments codes",
    #     description="A collection of invertebrate active sampling capture "
    #     "equipments and its codes.",
    #     collection_uuid="59bcbbfb-151d-48b4-ae27-a46638c466dc",
    #     uuid_namespace="invertebrate active sampling capture equipments",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-invertebrate-active-sampling-search-methods",
    #     label="Invertebrate active sampling search methods codes",
    #     description="A collection of invertebrate active sampling search "
    #     "methods and its codes.",
    #     collection_uuid="1701eb2d-5d7e-4fcf-939a-52a953494d25",
    #     uuid_namespace="invertebrate active sampling search methods",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-invertebrate-active-sampling-search-types",
    #     label="Invertebrate active sampling search types codes",
    #     description="A collection of invertebrate active sampling search "
    #     "types and its codes.",
    #     collection_uuid="85cfdd2b-2dd3-4496-a084-09cd4d0456d8",
    #     uuid_namespace="invertebrate active sampling search types",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-invertebrate-liquid-types",
    #     label="Invertebrate liquid types codes",
    #     description="A collection of invertebrate liquid types and its codes.",
    #     collection_uuid="5a11c221-05fe-4798-88f7-8e7488668484",
    #     uuid_namespace="invertebrate liquid types",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-invertebrate-malaise-trapping-voucher-types",
    #     label="Invertebrate malaise trapping voucher types codes",
    #     description="A collection of invertebrate malaise trapping voucher "
    #     "types and its codes.",
    #     collection_uuid="0934092d-dbc4-455d-9eb2-1a621ade3c7c",
    #     uuid_namespace="invertebrate malaise trapping voucher types",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-invertebrate-pan-trap-line-ids",
    #     label="Invertebrate pan trap line ids codes",
    #     description="A collection of invertebrate pan trap line ids and its codes.",
    #     collection_uuid="c66abea7-93a0-48b3-9680-874198fccd30",
    #     uuid_namespace="invertebrate pan trap line ids",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-invertebrate-pan-trapping-colours",
    #     label="Invertebrate pan trapping colours codes",
    #     description="A collection of invertebrate pan trapping colours and "
    #     "its codes.",
    #     collection_uuid="3532bfc2-8fa1-48c4-a785-e6181735f232",
    #     uuid_namespace="invertebrate pan trapping colours",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-invertebrate-pan-trapping-durations",
    #     label="Invertebrate pan trapping durations codes",
    #     description="A collection of invertebrate pan trapping durations "
    #     "and its codes.",
    #     collection_uuid="0c804744-c05d-4dc2-8a4b-a048282b2bbd",
    #     uuid_namespace="invertebrate pan trapping durations",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-invertebrate-post-field-guideline-groups",
    #     label="Invertebrate post field guideline groups codes",
    #     description="A collection of invertebrate post field guideline "
    #     "groups and its codes.",
    #     collection_uuid="5174e669-328b-4df8-879e-95b13738f475",
    #     uuid_namespace="invertebrate post field guideline groups",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-invertebrate-post-field-guideline-life-stages",
    #     label="Invertebrate post field guideline life stages codes",
    #     description="A collection of invertebrate post field guideline life "
    #     "stages and its codes.",
    #     collection_uuid="e8659ef7-fe60-4484-be17-0ed9c1495b97",
    #     uuid_namespace="invertebrate post field guideline life stages",
    # ),
    LUTSchema(
        endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-landform-elements",
        label="Landform element types",
        description="A collection of the types of landform elements such as a Dune, Gully, Hillcrest, Estuary, etc.",
        collection_url="https://linked.data.gov.au/def/nrm/c1a58967-cb12-4c2c-a7ca-9cee2589919c",
        uuid_namespace="landform element",
    ),
    LUTSchema(
        endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-landform-patterns",
        label="landform pattern types",
        description="A collection of the types of landform patterns such as a Delta, Lava Plain, Tidal Flat, etc.",
        collection_url="https://linked.data.gov.au/def/nrm/19d91a7a-2733-4b84-9d2b-4bda4808c003",
        uuid_namespace="landform pattern",
    ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-leaf-litter-sample-preservations",
    #     label="Leaf litter sample preservations codes",
    #     description="A collection of leaf litter sample preservations and "
    #     "its codes.",
    #     collection_uuid="38674fef-988c-4fa4-b8e6-0b06e2bd5f4f",
    #     uuid_namespace="leaf litter sample preservations",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-light-trap-types",
    #     label="Light trap types codes",
    #     description="A collection of light trap types and its codes.",
    #     collection_uuid="33e5036f-3560-4b0b-87dd-c570cec0359a",
    #     uuid_namespace="light trap types",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-identification-methods",
    #     label="Method of identification codes",
    #     description="A collection of method of identification types and its codes.",
    #     collection_uuid="43c7a4be-72f3-4007-9777-7e7aa2d8da25",
    #     uuid_namespace="method of identification",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-tier-1-microhabitats",
    #     label="Microhabitat tier 1 codes",
    #     description="A collection of microhabitat tier 1 types and its codes.",
    #     collection_uuid="66034d49-50d7-4042-a252-c2bd249d2a4b",
    #     uuid_namespace="microhabitat tier 1",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-tier-2-microhabitats",
    #     label="Microhabitat codes",
    #     description="A collection of microhabitat types and its codes.",
    #     collection_uuid="48f0bb5d-5451-42a1-ad60-7ddca485412d",
    #     uuid_namespace="microhabitat",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-microhabitats",
    #     label="Microhabitat (tier 2) codes",
    #     description="A collection of microhabitats (tier 2) and its codes.",
    #     collection_uuid="2cf23037-6afa-4523-8e9f-0bd86190ccc8",
    #     uuid_namespace="microhabitats tier 2",
    # ),
    LUTSchema(
        endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-tier-1-observation-methods",
        label="Observation methods tier 1",
        description="A collection of observation methods (tier 1) used during a fauna survey. Some examples of tier 1 method include simple observations, such as 'seen', 'sign', 'heard', etc.",
        collection_url="https://linked.data.gov.au/def/nrm/6b6ec6a4-33d2-4515-b988-617d190cfbdb",
        uuid_namespace="observation method tier 1",
    ),
    LUTSchema(
        endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-tier-2-observation-methods",
        label="Observation methods tier 2",
        description="A collection of observation methods (tier 2) used during a fauna survey. Some examples of tier 2 method include observations such as 'spotlighting', 'scat', 'skin', 'scratchings', 'bone/teeth', 'diggings', 'tracks', etc.",
        collection_url="https://linked.data.gov.au/def/nrm/f1592e71-cc16-4b81-90c4-06b418a5a766",
        uuid_namespace="observation method tier 2",
    ),
    LUTSchema(
        endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-tier-3-observation-methods",
        label="Observation methods tier 3",
        description="A collection of unique identifier codes used during an opportune observation methods - tier 3.",
        collection_url="https://linked.data.gov.au/def/nrm/bf0e07c4-0977-4a97-9e82-11691641ca2e",
        uuid_namespace="observation methods tier 3",
    ),
    LUTSchema(
        endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-floristics-phenologies",
        label="phenological stages",
        description="A collection of plant phenological stages. Examples include plants in flower, fruit, buds, senescent, etc.",
        collection_url="https://linked.data.gov.au/def/nrm/110398ca-32fa-4f69-b7bb-5aa69d5a5004",
        uuid_namespace="phenology type",
    ),
    LUTSchema(
        endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-slope-classes",
        label="slope classes",
        description="A collection of eight slope classes used when describing the landform of the plot. Some examples of slope classes include, 'level'- a slope percent of 0-10%, 'steep'- a slope percent of 35-56%, 'cliff'- a slope percent of >301.",
        collection_url="https://linked.data.gov.au/def/nrm/d893e669-c530-4bc3-a057-a5799ffcb5db",
        uuid_namespace="plot slope",
    ),
    LUTSchema(
        endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-preservation-types",
        label="Preservation types",
        description="Refers to a collection of methods of preservation/preservatives used to preserve/voucher fauna specimens. The collection includes, methods such as 'dried and stored', using a 'Dry ice (solid CO2)', 'Ethanol' - denatured or undenatured, 'Ethanol/formalin mixed solution', 'Fixed (smear)', 'Formalin', 'Frozen (domestic freezer -20°C)', 'Liquid nitrogen (N2)', 'Methylated spirits', 'Propylene glycol', 'Refrigerated', 'Saline solution' and 'Silica'.",
        collection_url="https://linked.data.gov.au/def/nrm/4e5037f1-97e6-4866-a018-915bcf482261",
        uuid_namespace="preservation type",
    ),
    LUTSchema(
        endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-floristics-habits",
        label="plant habit types",
        description="A collection of plant habit types. Examples include climbing, erect, procumbent, decumbent, pendulous plants, etc.",
        collection_url="https://linked.data.gov.au/def/nrm/015360a2-1e21-4401-be70-25c581569ba6",
        uuid_namespace="plant habit type",
    ),
    LUTSchema(
        endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-fractional-cover-intercepts",
        label="Fractional cover response types",
        description="A collection of the types of fraction cover responses. Examples are Branch, Non-photosynthetic vegetation and Photosynthetic Vegetation",
        collection_url="https://linked.data.gov.au/def/nrm/51d1a677-0688-57b3-91c7-6f1e3beee188",
        uuid_namespace="fractional cover response",
    ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-protocol-variants",
    #     label="Protocol variants codes",
    #     description="A collection of protocol variants and its codes.",
    #     collection_uuid="5d96e377-fb3a-4735-875d-4bad4df46c79",
    #     uuid_namespace="protocol variants",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-recruitment-healths",
    #     label="Vegetation healths codes",
    #     description="A collection of vegetation healths and its codes.",
    #     collection_uuid="785f818c-0c8c-480b-b8e5-43ea9fda70f0",
    #     uuid_namespace="recruitment healths",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-recruitment-study-area-types",
    #     label="Recruitment study area types codes",
    #     description="A collection of recruitment study area types and its codes.",
    #     collection_uuid="f22918eb-77d5-47af-b5c9-4a7a561288e7",
    #     uuid_namespace="recruitment study area types",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-recruitment-transects",
    #     label="Recruitment transects codes",
    #     description="A collection of recruitment transect numbers and its codes.",
    #     collection_uuid="baa1ee46-d49b-47cf-8dbb-a70aad01f06c",
    #     uuid_namespace="recruitment transect numbers",
    # ),
    LUTSchema(
        endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-recruitment-tree-statuses",
        label="Plant statuses",
        description="Refers to whether a plant is 'alive' or 'dead'.",
        collection_url="https://linked.data.gov.au/def/nrm/b7368a37-a4ac-4c84-8a78-1fb9755ad849",
        uuid_namespace="recruitment tree statuses",
    ),
    LUTSchema(
        endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-lithologies",
        label="soil lithology types",
        description="A collection of parent rock and unconsolidated materials. Some examples include rocks that are of igneous origin such as, Adamellite, Andesite, Diorite, etc., or rocks that are sedimentary, such as Alcrete, Calcrete, Coal to name a few.",
        collection_url="https://linked.data.gov.au/def/nrm/1d50eb79-685f-45ea-84b4-627154eddede",
        uuid_namespace="soil lithology",
    ),
    LUTSchema(
        endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-substrates",
        label="Substrate types",
        description="A collection of land surface substrate types. Some examples include bare, black ash, crypto, coarse woody debris, litter, etc.",
        collection_url="https://linked.data.gov.au/def/nrm/b061d7db-a608-4062-96d4-b367d6d9a792",
        uuid_namespace="soil substrate",
    ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-surface-strew-sizes",
    #     label="Soil surface strew size codes",
    #     description="A collection of soil surface strew size types and its codes.",
    #     collection_uuid="3b25ce0f-9eb7-4d2d-97ce-143858cfd4d4",
    #     uuid_namespace="soil surface strew size",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-asc-classes",
    #     label="Soils asc classes codes",
    #     description="A collection of soils asc classes and its codes.",
    #     collection_uuid="430ebf92-824e-4dc6-9410-2b454fe8a063",
    #     uuid_namespace="soils asc classes",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-asc-families",
    #     label="Soils asc families codes",
    #     description="A collection of soils asc families and its codes.",
    #     collection_uuid="21a22e29-b88f-4d6c-b7d7-7763de409560",
    #     uuid_namespace="soils asc families",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-asc-orders",
    #     label="Soils asc orders codes",
    #     description="A collection of soils asc orders and its codes.",
    #     collection_uuid="cd377ef2-2174-4c7b-a6ef-7e0b1f83b85a",
    #     uuid_namespace="soils asc orders",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-biotic-relief-agents",
    #     label="Soils biotic relief agents codes",
    #     description="A collection of soils biotic relief agents and its codes.",
    #     collection_uuid="70b3ea97-90dd-49f7-9ca2-717a8deb6368",
    #     uuid_namespace="soils biotic relief agents",
    # ),
    LUTSchema(
        endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-coarse-frag-abundances",
        label="soil coarse fragments abundance types",
        description="A collection of the types of abundance (percentage) of soil coarse fragments. The percentage can vary from '0'- no coarse fragments to '>90%'- extremely abundant.",
        collection_url="https://linked.data.gov.au/def/nrm/bec608c4-3a66-4630-b666-cabb666ac8d2",
        uuid_namespace="soils coarse frag abundances",
    ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-coarse-frag-alterations",
    #     label="Soils coarse fragment alterations codes",
    #     description="A collection of soils coarse fragment alterations and its codes.",
    #     collection_uuid="87f4f5fc-d24d-4865-9b11-9ca9ac5e159f",
    #     uuid_namespace="soils coarse frag alterations",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-coarse-frag-shapes",
    #     label="Soils coarse fragment shapes codes",
    #     description="A collection of soils coarse fragment shapes and its codes.",
    #     collection_uuid="13c84b19-e2bb-48c4-93db-465bcad2dbb5",
    #     uuid_namespace="soils coarse frag shapes",
    # ),
    LUTSchema(
        endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-coarse-frag-sizes",
        label="soil coarse fragments sizes",
        description="A collection of various size classes of soil coarse fragments. Sizes can vary from extremely Large Boulders (>2000 mm) or Bouldery (600-2000 mm) to medium gravelly or pebbles (6-20mm) or fine gravelly (2-6mm).",
        collection_url="https://linked.data.gov.au/def/nrm/06d01bf1-3863-44ea-95fe-4c62bb47b996",
        uuid_namespace="soils coarse frag sizes",
    ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-coarse-frag-strengths",
    #     label="Soils coarse fragment strengths codes",
    #     description="A collection of soils coarse fragment strengths and its codes.",
    #     collection_uuid="1ac1c1c1-5a64-47e4-b593-aabfefd57e46",
    #     uuid_namespace="soils coarse frag strengths",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-confidence-levels",
    #     label="Soils confidence levels codes",
    #     description="A collection of soils confidence levels and its codes.",
    #     collection_uuid="7bd6fc9b-2e65-4cdd-acda-8cab19f2cefe",
    #     uuid_namespace="soils confidence levels",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-cutan-abundances",
    #     label="Soils cutan abundances codes",
    #     description="A collection of soils cutan abundances and its codes.",
    #     collection_uuid="984fbd63-e521-4fef-80f9-bcb9307a76a9",
    #     uuid_namespace="soils cutan abundances",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-cutan-distinctnesses",
    #     label="Soils cutan distinctnesses codes",
    #     description="A collection of soils cutan distinctnesses and its codes.",
    #     collection_uuid="e9ea1cd7-4e33-4086-b0ce-cd2f00c2b8ad",
    #     uuid_namespace="soils cutan distinctnesses",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-cutan-types",
    #     label="Soils cutan types codes",
    #     description="A collection of soils cutan types and its codes.",
    #     collection_uuid="e2e7323b-774a-4be0-a40d-2d52e042dd17",
    #     uuid_namespace="soils cutan types",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-digging-stopped-bies",
    #     label="Soils digging stopped by codes",
    #     description="A collection of soils digging stopped by and its codes.",
    #     collection_uuid="d9a651b0-efd1-4fe5-b229-d350b9756846",
    #     uuid_namespace="soils digging stopped bies",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-drainages",
    #     label="Soils drainages codes",
    #     description="A collection of soils drainages and its codes.",
    #     collection_uuid="0c9132dc-48bf-4a9c-ac9b-0c8b1909afb4",
    #     uuid_namespace="soils drainages",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-effervescences",
    #     label="Soils effervescences codes",
    #     description="A collection of soils effervescences and its codes.",
    #     collection_uuid="4f3a874f-4629-498a-b270-6880ca43b3a6",
    #     uuid_namespace="soils effervescences",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-erosion-states",
    #     label="Soils erosion states codes",
    #     description="A collection of soils erosion states and its codes.",
    #     collection_uuid="e7087186-7027-42c3-ab54-b65a39034dd1",
    #     uuid_namespace="soils erosion states",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-erosion-types",
    #     label="Soils erosion types codes",
    #     description="A collection of soils erosion types and its codes.",
    #     collection_uuid="4f3d9522-e612-40ef-ab8a-7d77960c9f8f",
    #     uuid_namespace="soils erosion types",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-evaluation-means",
    #     label="Soils evaluation means codes",
    #     description="A collection of soils evaluation means and its codes.",
    #     collection_uuid="18e48ca5-1b36-4c20-8a12-4e04bb916a01",
    #     uuid_namespace="soils evaluation means",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-fabric-details",
    #     label="Soils fabric details codes",
    #     description="A collection of soils fabric details and its codes.",
    #     collection_uuid="2d1d8394-6641-4d74-988a-8ec66425ffdd",
    #     uuid_namespace="soils fabric details",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-field-dispersion-scores",
    #     label="Soils field dispersion scores codes",
    #     description="A collection of soils field dispersion scores and its codes.",
    #     collection_uuid="0e0a3e73-4b7a-4ffb-8b91-ee0748688bb1",
    #     uuid_namespace="soils field dispersion scores",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-field-slaking-scores",
    #     label="Soils field slaking scores codes",
    #     description="A collection of soils field slaking scores and its codes.",
    #     collection_uuid="c2408628-477b-4867-bc12-532126801973",
    #     uuid_namespace="soils field slaking scores",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-fine-macropore-abundances",
    #     label="Soils fine macropore abundances codes",
    #     description="A collection of soils fine macropore abundances and its codes.",
    #     collection_uuid="5c685afb-1a56-4261-93f1-8440fbc65ef3",
    #     uuid_namespace="soils fine macropore abundances",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-gilgal-proportions",
    #     label="Soils gilgal proportions codes",
    #     description="A collection of soils gilgal proportions and its codes.",
    #     collection_uuid="c441cb41-6f65-417c-88b7-2c10375bf3f3",
    #     uuid_namespace="soils gilgal proportions",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-gully-depths",
    #     label="Soils gully depths codes",
    #     description="A collection of soils gully depths and its codes.",
    #     collection_uuid="7f0eb236-c8e8-4473-8f11-214487ba1d8a",
    #     uuid_namespace="soils gully depths",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-gully-water-erosion-degrees",
    #     label="Soils gully water erosion degrees codes",
    #     description="A collection of soils gully water erosion degrees and "
    #     "its codes.",
    #     collection_uuid="42898383-1e9f-4d61-bd60-fca4669c1e05",
    #     uuid_namespace="soils gully water erosion degrees",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-horizon-boundary-distinctnesses",
    #     label="Soils horizon boundary distinctnesses codes",
    #     description="A collection of soils horizon boundary distinctnesses "
    #     "and its codes.",
    #     collection_uuid="1c6b54da-bb31-4496-974e-050531b15e30",
    #     uuid_namespace="soils horizon boundary distinctnesses",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-horizon-boundary-shapes",
    #     label="Soils horizon boundary shapes codes",
    #     description="A collection of soils horizon boundary shapes and its codes.",
    #     collection_uuid="2f514fb5-6c23-4fff-beed-858722a0f586",
    #     uuid_namespace="soils horizon boundary shapes",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-horizon-details",
    #     label="Soils horizon details codes",
    #     description="A collection of soils horizon details and its codes.",
    #     collection_uuid="bcd57c16-0e94-48c9-aee7-296a0e13b3ca",
    #     uuid_namespace="soils horizon details",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-horizon-suffixes",
    #     label="Soils horizon suffixes codes",
    #     description="A collection of soils horizon suffixes and its codes.",
    #     collection_uuid="31d3921f-1fcb-4ec2-99a6-749c7b9e4798",
    #     uuid_namespace="soils horizon suffixes",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-horizon-typicals",
    #     label="Soils horizon typicals codes",
    #     description="A collection of soils horizon typicals and its codes.",
    #     collection_uuid="3fa6ec81-4451-477a-910f-0107ae8032bb",
    #     uuid_namespace="soils horizon typicals",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-macropore-diameters",
    #     label="Soils macropore diameters codes",
    #     description="A collection of soils macropore diameters and its codes.",
    #     collection_uuid="3c3ccc22-949a-4892-9c51-7b458a823fcd",
    #     uuid_namespace="soils macropore diameters",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-mass-movement-erosion-degrees",
    #     label="Soils mass movement erosion degrees codes",
    #     description="A collection of soils mass movement erosion degrees "
    #     "and its codes.",
    #     collection_uuid="c417aca7-46ef-42ae-90f0-6fb00ed9e357",
    #     uuid_namespace="soils mass movement erosion degrees",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-medium-macropore-abundances",
    #     label="Soils medium macropore abundances codes",
    #     description="A collection of soils medium macropore abundances and "
    #     "its codes.",
    #     collection_uuid="ee3a4058-d8de-43b8-a002-3f072f039b75",
    #     uuid_namespace="soils medium macropore abundances",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-microrelief-components",
    #     label="Soils microrelief components codes",
    #     description="A collection of soils microrelief components and its codes.",
    #     collection_uuid="2bf9967f-c699-4193-9b4d-744e68efd1ad",
    #     uuid_namespace="soils microrelief components",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-microrelief-gilgals",
    #     label="Soils microrelief gilgals codes",
    #     description="A collection of soils microrelief gilgals and its codes.",
    #     collection_uuid="ca5e075d-fc73-4953-8564-18e9e15175cb",
    #     uuid_namespace="soils microrelief gilgals",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-microrelief-hummockies",
    #     label="Soils microrelief hummockies codes",
    #     description="A collection of soils microrelief hummockies and its codes.",
    #     collection_uuid="594ae399-a2bf-4177-9cd7-c74cec57b287",
    #     uuid_namespace="soils microrelief hummockies",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-microrelief-types",
    #     label="Soils microrelief types codes",
    #     description="A collection of soils microrelief types and its codes.",
    #     collection_uuid="457faa4f-74e8-4b8a-9e4b-541bb7c50441",
    #     uuid_namespace="soils microrelief types",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-modal-slopes",
    #     label="Soils modal slopes codes",
    #     description="A collection of soils modal slopes and its codes.",
    #     collection_uuid="443bf3da-0f2b-42ad-b9a5-b9608159556a",
    #     uuid_namespace="soils modal slopes",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-moisture-statuses",
    #     label="Soils moisture statuses codes",
    #     description="A collection of soils moisture statuses and its codes.",
    #     collection_uuid="a1e434a8-3fbb-4323-a0ae-0e31308eba8b",
    #     uuid_namespace="soils moisture statuses",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-morphological-types",
    #     label="Soils morphological types codes",
    #     description="A collection of soils morphological types and its codes.",
    #     collection_uuid="50e0e5aa-3abf-4883-a713-245701efe314",
    #     uuid_namespace="soils morphological types",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-mottle-abundances",
    #     label="Soils mottle abundances codes",
    #     description="A collection of soils mottle abundances and its codes.",
    #     collection_uuid="100f6f80-d438-465a-8f57-5a76a038b961",
    #     uuid_namespace="soils mottle abundances",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-mottle-boundary-distinctnesses",
    #     label="Soils mottle boundary distinctnesses codes",
    #     description="A collection of soils mottle boundary distinctnesses "
    #     "and its codes.",
    #     collection_uuid="51622960-af4e-4398-82ca-a17223de1431",
    #     uuid_namespace="soils mottle boundary distinctnesses",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-mottle-colours",
    #     label="Soils mottle colours codes",
    #     description="A collection of soils mottle colours and its codes.",
    #     collection_uuid="a6d2b7d3-fe4f-4bf6-82ce-d53ae951cb7d",
    #     uuid_namespace="soils mottle colours",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-mottle-contrasts",
    #     label="Soils mottle contrasts codes",
    #     description="A collection of soils mottle contrasts and its codes.",
    #     collection_uuid="a0f8cc94-abbd-482b-8947-6017bc5f55e5",
    #     uuid_namespace="soils mottle contrasts",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-mottle-sizes",
    #     label="Soils mottle sizes codes",
    #     description="A collection of soils mottle sizes and its codes.",
    #     collection_uuid="c8dd7af4-8e57-4f59-848a-66712349754a",
    #     uuid_namespace="soils mottle sizes",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-mottle-types",
    #     label="Soils mottle types codes",
    #     description="A collection of soils mottle types and its codes.",
    #     collection_uuid="b12461fc-166e-477b-a58c-60682848010e",
    #     uuid_namespace="soils mottle types",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-observation-types",
    #     label="Soils observation types codes",
    #     description="A collection of soils observation types and its codes.",
    #     collection_uuid="53e41f87-1104-4454-b296-a4068c3f7568",
    #     uuid_namespace="soils observation types",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-pan-cementations",
    #     label="Soils pan cementations codes",
    #     description="A collection of soils pan cementations and its codes.",
    #     collection_uuid="ad3e7729-fbe4-4b93-8428-74f6ced865c1",
    #     uuid_namespace="soils pan cementations",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-pan-continuities",
    #     label="Soils pan continuities codes",
    #     description="A collection of soils pan continuities and its codes.",
    #     collection_uuid="c80e269f-a328-4214-b690-849259e67e75",
    #     uuid_namespace="soils pan continuities",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-pan-structures",
    #     label="Soils pan structures codes",
    #     description="A collection of soils pan structures and its codes.",
    #     collection_uuid="295ca7cc-f6e6-451d-a0de-667fa3187378",
    #     uuid_namespace="soils pan structures",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-pan-types",
    #     label="Soils pan types codes",
    #     description="A collection of soils pan types and its codes.",
    #     collection_uuid="995adb71-6439-4cd3-9ece-bb87a8a217c0",
    #     uuid_namespace="soils pan types",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-permeabilities",
    #     label="Soils permeabilities codes",
    #     description="A collection of soils permeabilities and its codes.",
    #     collection_uuid="41a54b21-b885-4cfd-be09-7bedc4ae4dc4",
    #     uuid_namespace="soils permeabilities",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-relative-inclination-of-slope-elements",
    #     label="Soils relative inclination of slope elements codes",
    #     description="A collection of soils relative inclination of slope "
    #     "elements and its codes.",
    #     collection_uuid="844f1b7a-6a65-4994-9526-c337d84a7652",
    #     uuid_namespace="soils relative inclination of slope elements",
    # ),
    LUTSchema(
        endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-plot-reliefs",
        label="Soil reliefs",
        description="A collection of the types of soil reliefs. They range from: 'Extremely low (<9m)', 'Low (30-90m)',  'Very low (9-30 m)', 'High (90-300 m)', and 'Very high (>300 m)'.",
        collection_url="https://linked.data.gov.au/def/nrm/9e377f67-190e-4d58-9ec9-adebedaf14e2",
        uuid_namespace="soils reliefs",
    ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-rill-water-erosion-degrees",
    #     label="Soils rill water erosion degrees codes",
    #     description="A collection of soils rill water erosion degrees and "
    #     "its codes.",
    #     collection_uuid="c5bb4782-a8c7-4293-b6f0-b53c6c808f5f",
    #     uuid_namespace="soils rill water erosion degrees",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-rock-outcrop-abundances",
    #     label="Soils rock outcrop abundances codes",
    #     description="A collection of soils rock outcrop abundances and its codes.",
    #     collection_uuid="c06f57b7-fde3-47c6-b410-8db0ec7e68e1",
    #     uuid_namespace="soils rock outcrop abundances",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-runoffs",
    #     label="Soils runoffs codes",
    #     description="A collection of soils runoffs and its codes.",
    #     collection_uuid="bcc7bb4d-a15a-4681-94e0-cb7a1117420a",
    #     uuid_namespace="soils runoffs",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-scald-erosion-degrees",
    #     label="Soils scald erosion degrees codes",
    #     description="A collection of soils scald erosion degrees and its codes.",
    #     collection_uuid="941e13e1-1bb3-471b-8502-9dc366c1dbf7",
    #     uuid_namespace="soils scald erosion degrees",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-segregation-magnetic-attributes",
    #     label="Soils segregation magnetic attributes codes",
    #     description="A collection of soils segregation magnetic attributes "
    #     "and its codes.",
    #     collection_uuid="f503ff93-f7d7-4419-9d1e-6807e96dc2c1",
    #     uuid_namespace="soils segregation magnetic attributes",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-segregations-abundances",
    #     label="Soils segregations abundances codes",
    #     description="A collection of soils segregations abundances and its codes.",
    #     collection_uuid="9b4820fb-6ee1-439c-8972-f642b9a7b5f8",
    #     uuid_namespace="soils segregations abundances",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-segregations-forms",
    #     label="Soils segregations forms codes",
    #     description="A collection of soils segregations forms and its codes.",
    #     collection_uuid="e2a473c3-a2e3-44fc-a309-a662c6e53542",
    #     uuid_namespace="soils segregations forms",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-segregations-natures",
    #     label="Soils segregations natures codes",
    #     description="A collection of soils segregations natures and its codes.",
    #     collection_uuid="2e870427-8563-4d61-b7ac-3556aaf0cbf2",
    #     uuid_namespace="soils segregations natures",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-segregations-sizes",
    #     label="Soils segregations sizes codes",
    #     description="A collection of soils segregations sizes and its codes.",
    #     collection_uuid="f795d7e8-1bc9-4efa-98b7-e19717c66282",
    #     uuid_namespace="soils segregations sizes",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-sheet-water-erosion-degrees",
    #     label="Soils sheet water erosion degrees codes",
    #     description="A collection of soils sheet water erosion degrees and "
    #     "its codes.",
    #     collection_uuid="7d0706e7-4424-486b-a501-1958c660110b",
    #     uuid_namespace="soils sheet water erosion degrees",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-soil-strengths",
    #     label="Soils soil strengths codes",
    #     description="A collection of soils soil strengths and its codes.",
    #     collection_uuid="9f599dbb-458f-4d8a-846a-fd1a080f8853",
    #     uuid_namespace="soils soil strengths",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-stream-bank-water-erosion-degrees",
    #     label="Soils stream bank water erosion degrees codes",
    #     description="A collection of soils stream bank water erosion "
    #     "degrees and its codes.",
    #     collection_uuid="f62945ca-2eeb-4055-a9cc-187185948d65",
    #     uuid_namespace="soils stream bank water erosion degrees",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-structure-compound-pedalities",
    #     label="Soils structure compound pedalities codes",
    #     description="A collection of soils structure compound pedalities "
    #     "and its codes.",
    #     collection_uuid="75de6044-7575-472a-9a72-2c9006a8c9b1",
    #     uuid_namespace="soils structure compound pedalities",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-structure-grades",
    #     label="Soils structure grades codes",
    #     description="A collection of soils structure grades and its codes.",
    #     collection_uuid="0cfcb0fc-75e3-4de1-a2d3-78c357a3ce06",
    #     uuid_namespace="soils structure grades",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-structure-sizes",
    #     label="Soils structure sizes codes",
    #     description="A collection of soils structure sizes and its codes.",
    #     collection_uuid="f5226b34-eac7-42c3-9730-b7fdb2479697",
    #     uuid_namespace="soils structure sizes",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-structure-types",
    #     label="Soils structure types codes",
    #     description="A collection of soils structure types and its codes.",
    #     collection_uuid="ba792941-7941-43c8-b992-b7f54dddf14c",
    #     uuid_namespace="soils structure types",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-surface-soil-conditions",
    #     label="Soils surface soil conditions codes",
    #     description="A collection of soils surface soil conditions and its codes.",
    #     collection_uuid="253cc4d0-b1f2-4a55-bdaf-e3c054703451",
    #     uuid_namespace="soils surface soil conditions",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-texture-grades",
    #     label="Soils texture grades codes",
    #     description="A collection of soils texture grades and its codes.",
    #     collection_uuid="ecdcb81a-cbe9-4113-b9e9-422a0e6c751f",
    #     uuid_namespace="soils texture grades",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-texture-modifiers",
    #     label="Soils texture modifiers codes",
    #     description="A collection of soils texture modifiers and its codes.",
    #     collection_uuid="65d26894-1b2e-4c80-92ee-fa420142ed67",
    #     uuid_namespace="soils texture modifiers",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-texture-qualifications",
    #     label="Soils texture qualifications codes",
    #     description="A collection of soils texture qualifications and its codes.",
    #     collection_uuid="367b9d17-0e08-4ad4-9c44-20e8c3f515fb",
    #     uuid_namespace="soils texture qualifications",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-tunnel-water-erosion-degrees",
    #     label="Soils tunnel water erosion degrees codes",
    #     description="A collection of soils tunnel water erosion degrees and "
    #     "its codes.",
    #     collection_uuid="b0e01539-05b6-4dc8-8a27-019c8fb5eeec",
    #     uuid_namespace="soils tunnel water erosion degrees",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-void-cracks",
    #     label="Soils void cracks codes",
    #     description="A collection of soils void cracks and its codes.",
    #     collection_uuid="1acac98b-808d-4efa-aa27-a0cb7782e63f",
    #     uuid_namespace="soils void cracks",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-water-statuses",
    #     label="Soils water statuses codes",
    #     description="A collection of soils water statuses and its codes.",
    #     collection_uuid="e1573937-3a4e-4df6-beba-29e25e7c5596",
    #     uuid_namespace="soils water statuses",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-wind-erosion-degrees",
    #     label="Soils wind erosion degrees codes",
    #     description="A collection of soils wind erosion degrees and its codes.",
    #     collection_uuid="5c1ef6e3-2da4-4fb2-be2c-3e92a93fe545",
    #     uuid_namespace="soils wind erosion degrees",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-identification-sources",
    #     label="Source of identification codes",
    #     description="A collection of source of identification types and its codes.",
    #     collection_uuid="a36600ac-b9ed-44d1-b199-85ee1d802e58",
    #     uuid_namespace="source of identification",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-specimen-locations",
    #     label="Specimen location codes",
    #     description="A collection of specimen location types and its codes.",
    #     collection_uuid="1df5afd1-475a-435a-94c5-143b707aab10",
    #     uuid_namespace="specimen location",
    # ),
    LUTSchema(
        endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-states",
        label="States and Territories",
        description="A collection of Australian States and Territories.",
        collection_url="https://linked.data.gov.au/def/nrm/0a71eab7-3989-4c35-82c0-1e746c36b291",
        uuid_namespace="states",
    ),
    LUTSchema(
        endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-veg-associations",
        label="Stratum types",
        description="A collection of Vegetation Stratum layers as recognised by the Australian National Vegetation Information System (NVIS). These include: the 'Upper', 'Middle' and 'Ground' strata.",
        collection_url="https://linked.data.gov.au/def/nrm/eb6e9a4c-e277-4cb3-9792-9c91311b7e03",
        uuid_namespace="stratum type",
    ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-substratum-types",
    #     label="Substratum type codes",
    #     description="A collection of substratum types and its codes.",
    #     collection_uuid="7fc2cae5-74f6-426d-a25d-cbf9423b572a",
    #     uuid_namespace="substratum type",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-targeted-fauna-survey-types",
    #     label="Targeted fauna survey types codes",
    #     description="A collection of targeted fauna survey types and its codes.",
    #     collection_uuid="70518904-e523-412e-8d3a-cdeae47a79e0",
    #     uuid_namespace="targeted fauna survey types",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-targeted-survey-fauna-passive-equipments",
    #     label="Targeted survey fauna passive equipments codes",
    #     description="A collection of targeted survey fauna passive "
    #     "equipments and its codes.",
    #     collection_uuid="d1df6208-dec2-4f9c-91a8-2c00fc7835c1",
    #     uuid_namespace="targeted survey fauna passive equipments",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-targeted-survey-fauna-vouchers",
    #     label="Targeted survey fauna vouchers codes",
    #     description="A collection of targeted survey fauna vouchers and its codes.",
    #     collection_uuid="cb1fc752-939d-4311-ab19-7b2bc80cf3f3",
    #     uuid_namespace="targeted survey fauna vouchers",
    # ),
    LUTSchema(
        endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-veg-growth-stages",
        label="Growth stages",
        description="A collection of dominant growth stages of plants. Examples include, 'Mature', 'Recruiting', 'Resprouting', 'Senescent', etc.",
        collection_url="https://linked.data.gov.au/def/nrm/096e018a-fb8f-4ba1-9fdc-302164e57682",
        uuid_namespace="targeted survey flora growth stages",
    ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-targeted-survey-general-survey-types",
    #     label="Targeted survey general survey types codes",
    #     description="A collection of targeted survey general survey types "
    #     "and its codes.",
    #     collection_uuid="7ca1606b-e8ed-4f7b-af2c-b3bdab30bae5",
    #     uuid_namespace="targeted survey general survey types",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-taxa-types",
    #     label="Taxa type codes",
    #     description="A collection of taxa types and its codes.",
    #     collection_uuid="7ea12fed-6b87-4c20-9ab4-600b32ce15ec",
    #     uuid_namespace="taxa type",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-tecs",
    #     label="Threatened ecological communities codes",
    #     description="A collection of tecs and its codes.",
    #     collection_uuid="0e718c57-74b4-441c-bf2d-3bfeff78b131",
    #     uuid_namespace="threatened ecological communities",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-temperature-units",
    #     label="Temperature units codes",
    #     description="A collection of temperature units and its codes.",
    #     collection_uuid="9c18266d-fe78-4ea7-ae42-a47d6c21dde6",
    #     uuid_namespace="temperature units",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-fauna-vagina-conditions",
    #     label="Vaginal condition codes",
    #     description="A collection of vaginal condition types and its codes.",
    #     collection_uuid="09de3b86-616e-49af-a34c-903cf7dec443",
    #     uuid_namespace="vaginal condition",
    # ),
    LUTSchema(
        endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-veg-growth-forms",
        label="Growth forms",
        description="A collection of vegetation growth forms adopted by the National Vegetation Information System (NVIS). Some examples include, Aquatic, Bryophyte, Chenopod, Cycad, Epiphyte, Fern, Forb, Grass, etc.",
        collection_url="https://linked.data.gov.au/def/nrm/d0fc07a7-3ec9-45ed-8850-885a32828d3c",
        uuid_namespace="vegetation growth form",
    ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-veg-height-classes",
    #     label="Vegetation height class codes",
    #     description="A collection of vegetation height class types and its codes.",
    #     collection_uuid="b1b05cd1-3b85-4639-a6af-799a34d88d43",
    #     uuid_namespace="vegetation height class",
    # ),
    LUTSchema(
        endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-veg-structural-formations",
        label="Vegetation structural formation types",
        description="A collection of various structural formation types as recognised by the Australian National Vegetation Information System (NVIS). Some examples include: Bryophyteland; Closed rushland; Forbland; Heathland; Isolated chenopod shrubs; Isolated clumps of rushes; and others listed in the NVIS classification.",
        collection_url="https://linked.data.gov.au/def/nrm/6e9baf51-566e-4a5d-93c4-a6e097dc364d",
        uuid_namespace="vegetation structural formation",
    ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-vegetation-types",
    #     label="Vegetation type codes",
    #     description="A collection of vegetation types and its codes.",
    #     collection_uuid="2f585fb4-996c-483c-9f9f-65e5bbd171b3",
    #     uuid_namespace="vegetation type",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-vertebrate-pitfall-trap-types",
    #     label="Vertebrate pitfall trap types codes",
    #     description="A collection of vertebrate pitfall trap types and its codes.",
    #     collection_uuid="fabad245-3057-4978-85db-26fb88c92667",
    #     uuid_namespace="vertebrate pitfall trap types",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-vertebrate-pouch-young-development-classes",
    #     label="Vertebrate pouch young development classes codes",
    #     description="A collection of vertebrate pouch young development "
    #     "classes and its codes.",
    #     collection_uuid="6a69b9e5-4a1e-4ef5-b79e-d8cea6e3d97b",
    #     uuid_namespace="vertebrate pouch young development classes",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-vertebrate-testes-positions",
    #     label="Vertebrate testes positions codes",
    #     description="A collection of vertebrate testes positions and its codes.",
    #     collection_uuid="6a46703e-dbc3-440e-b06f-217c400a18b5",
    #     uuid_namespace="vertebrate testes positions",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-vertebrate-trap-types",
    #     label="Vertebrate trap types codes",
    #     description="A collection of vertebrate trap types and its codes.",
    #     collection_uuid="fd2ab6f0-01b8-4216-bb7b-1e62eae4a40e",
    #     uuid_namespace="vertebrate trap types",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-voucher-conditions",
    #     label="Voucher condition codes",
    #     description="A collection of voucher condition types and its codes.",
    #     collection_uuid="600aa845-fe4d-4891-bf39-2e56220022cc",
    #     uuid_namespace="voucher condition",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-voucher-types",
    #     label="Voucher type codes",
    #     description="A collection of voucher types and its codes.",
    #     collection_uuid="a3333793-95bd-47fc-ba90-b8fc65a40456",
    #     uuid_namespace="voucher type",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-weather-cloud-covers",
    #     label="Weather cloud covers codes",
    #     description="A collection of weather cloud covers and its codes.",
    #     collection_uuid="b001aab8-d5c2-4268-a750-bed499386691",
    #     uuid_namespace="weather cloud covers",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-weather-precipitation-durations",
    #     label="Weather precipitation durations codes",
    #     description="A collection of weather precipitation durations and its codes.",
    #     collection_uuid="34789810-a3bc-4def-9ddb-d14ff4ba02ea",
    #     uuid_namespace="weather precipitation durations",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-weather-precipitations",
    #     label="Weather precipitations codes",
    #     description="A collection of weather precipitations and its codes.",
    #     collection_uuid="36e4cff5-f238-45e3-85ec-bdd0973f09d7",
    #     uuid_namespace="weather precipitations",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-weather-temperatures",
    #     label="Weather temperatures codes",
    #     description="A collection of weather temperatures and its codes.",
    #     collection_uuid="cd1530af-09a6-4666-98d5-580c0e65cf10",
    #     uuid_namespace="weather temperatures",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-weather-winds",
    #     label="Weather winds codes",
    #     description="A collection of weather winds and its codes.",
    #     collection_uuid="0fb03c4e-ad42-445a-a2c5-688d7d7effd8",
    #     uuid_namespace="weather winds",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-intervention-types",
    #     label="Intervention types codes",
    #     description="A collection of intervention types and its codes.",
    #     collection_uuid="b8bfa5aa-b405-454f-b581-f5a9a7aaf71f",
    #     uuid_namespace="intervention types",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-intervention-access-control-types",
    #     label="Intervention access control types codes",
    #     description="A collection of intervention access control types and its codes.",
    #     collection_uuid="28b46456-fc24-410c-93c9-6c9e4c2118f5",
    #     uuid_namespace="intervention access control types",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-intervention-initial-or-followups",
    #     label="Intervention initial or followups codes",
    #     description="A collection of intervention initial or followups and its codes.",
    #     collection_uuid="1e5bc3df-4765-4478-a9d3-23679c2d7241",
    #     uuid_namespace="intervention initial or followups",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-intervention-pest-controls",
    #     label="Intervention pest controls codes",
    #     description="A collection of intervention pest controls and its codes.",
    #     collection_uuid="41e62670-ee74-48fa-898c-9bc715009268",
    #     uuid_namespace="intervention pest controls",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-intervention-pest-population-types",
    #     label="Intervention pest population types codes",
    #     description="A collection of intervention pest population types and its codes.",
    #     collection_uuid="a6e5a078-b6d9-42a8-a1c6-a32ba6e68f91",
    #     uuid_namespace="intervention pest population types",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-intervention-debris-removal-types",
    #     label="Intervention debris removal types codes",
    #     description="A collection of intervention debris removal types and its codes.",
    #     collection_uuid="70690fe1-e803-4af0-ab6f-fb8f54456933",
    #     uuid_namespace="intervention debris removal types",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-intervention-erosion-treatment-types",
    #     label="Intervention erosion treatment types codes",
    #     description="A collection of intervention erosion treatment types and its codes.",
    #     collection_uuid="e168364e-0e5d-496f-a0a0-afa3f246ddab",
    #     uuid_namespace="intervention erosion treatment types",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-interventions-established-or-maintaineds",
    #     label="Interventions established or maintaineds codes",
    #     description="A collection of interventions established or maintaineds and its codes.",
    #     collection_uuid="2f992413-6361-405c-8462-f3727f99bd83",
    #     uuid_namespace="interventions established or maintaineds",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-intervention-individuals-or-groups",
    #     label="Intervention individuals or groups codes",
    #     description="A collection of intervention individuals or groups and its codes.",
    #     collection_uuid="9c0d6241-1938-430e-8f90-eb57f5a6676d",
    #     uuid_namespace="intervention individuals or groups",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-interventions-location-types",
    #     label="Interventions location types codes",
    #     description="A collection of interventions location types and its codes.",
    #     collection_uuid="200819a8-5172-4b8a-8261-784c13525d42",
    #     uuid_namespace="interventions location types",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-intervention-breeding-techniques",
    #     label="Intervention breeding techniques codes",
    #     description="A collection of intervention breeding techniques and its codes.",
    #     collection_uuid="e3378375-7841-4b73-bf88-c977cbecf623",
    #     uuid_namespace="intervention breeding techniques",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-intervention-survey-types",
    #     label="Intervention survey types codes",
    #     description="A collection of intervention survey types and its codes.",
    #     collection_uuid="b6e6afe3-9888-431c-b6ee-4610f07b5823",
    #     uuid_namespace="intervention survey types",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-intervention-fire-management-types",
    #     label="Intervention fire management types codes",
    #     description="A collection of intervention fire management types and its codes.",
    #     collection_uuid="d1d8a91d-5016-49ae-bee7-634c5e377e17",
    #     uuid_namespace="intervention fire management types",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-intervention-habitat-augmentation-types",
    #     label="Intervention habitat augmentation types codes",
    #     description="A collection of intervention habitat augmentation types and its codes.",
    #     collection_uuid="61962274-0474-473c-a845-08c69e9e04c5",
    #     uuid_namespace="intervention habitat augmentation types",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-intervention-installed-or-maintaineds",
    #     label="Intervention installed or maintaineds codes",
    #     description="A collection of intervention installed or maintaineds and its codes.",
    #     collection_uuid="5eab9792-08cc-4a1a-b82e-4b76b9331968",
    #     uuid_namespace="intervention installed or maintaineds",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-intervention-water-treament-management-types",
    #     label="Intervention water treament management types codes",
    #     description="A collection of intervention water treament management types and its codes.",
    #     collection_uuid="8d89b68a-22a5-48f9-af90-a8837dd21fb0",
    #     uuid_namespace="intervention water treament management types",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-intervention-land-management-action-types",
    #     label="Intervention land management action types codes",
    #     description="A collection of intervention land management action types and its codes.",
    #     collection_uuid="294edcdc-732f-48d2-845c-d9e687283b67",
    #     uuid_namespace="intervention land management action types",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-intervention-land-management-industry-types",
    #     label="Intervention land management industry types codes",
    #     description="A collection of intervention land management industry types and its codes.",
    #     collection_uuid="2d9702b7-209e-4a56-b707-6862763d17ed",
    #     uuid_namespace="intervention land management industry types",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-intervention-disease-management-or-treatment-types",
    #     label="Intervention disease management or treatment types codes",
    #     description="A collection of intervention disease management or treatment types and its codes.",
    #     collection_uuid="00c1d39b-6ef5-4967-bfa4-6feebd65336d",
    #     uuid_namespace="intervention disease management or treatment types",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-intervention-pest-animal-surveys",
    #     label="Intervention pest animal surveys codes",
    #     description="A collection of intervention pest animal surveys and its codes.",
    #     collection_uuid="68464ff8-3d98-462e-89e5-f14938f99845",
    #     uuid_namespace="intervention pest animal surveys",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-intervention-remediation-types",
    #     label="Intervention remediation types codes",
    #     description="A collection of intervention remediation types and its codes.",
    #     collection_uuid="ad745395-ec27-4306-acb2-4514c91800e5",
    #     uuid_namespace="intervention remediation types",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-intervention-weed-removal-treatment-types",
    #     label="Intervention weed removal treatment types codes",
    #     description="A collection of intervention weed removal treatment types and its codes.",
    #     collection_uuid="e25cf255-7576-44bb-83da-0f954ff1ba90",
    #     uuid_namespace="intervention weed removal treatment types",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-intervention-planting-methods",
    #     label="Intervention planting methods codes",
    #     description="A collection of intervention planting methods and its codes.",
    #     collection_uuid="dc02c4b7-cd30-4516-9730-b0682b54c5cf",
    #     uuid_namespace="intervention planting methods",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-intervention-seed-amounts",
    #     label="Intervention seed amounts codes",
    #     description="A collection of intervention seed amounts and its codes.",
    #     collection_uuid="08fe3752-df4b-4568-8977-33298a843e5d",
    #     uuid_namespace="intervention seed amounts",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-intervention-site-preparation-industry-types",
    #     label="Intervention site preparation industry types codes",
    #     description="A collection of intervention site preparation industry types and its codes.",
    #     collection_uuid="9e3f4698-4e02-414e-a673-c386476c846a",
    #     uuid_namespace="intervention site preparation industry types",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-intervention-site-preparation-action-types",
    #     label="Intervention site preparation action types codes",
    #     description="A collection of intervention site preparation action types and its codes.",
    #     collection_uuid="0b8508f8-a273-4d8c-8687-eabb35f30641",
    #     uuid_namespace="intervention site preparation action types",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-intervention-water-bodies",
    #     label="Intervention water bodies codes",
    #     description="A collection of intervention water bodies and its codes.",
    #     collection_uuid="772f6669-87ec-4348-a964-2e1bea2cbc23",
    #     uuid_namespace="intervention water bodies",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-wave-water-erosion-degrees",
    #     label="Soils wave water erosion degrees codes",
    #     description="A collection of soils wave water erosion degrees and its codes.",
    #     collection_uuid="58b549f7-45ce-452f-91cc-097b88eaf984",
    #     uuid_namespace="soils wave water erosion degrees",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-soils-segregation-strengths",
    #     label="Soils segregation strengths codes",
    #     description="A collection of soils segregation strengths and its codes.",
    #     collection_uuid="ff36816d-ee76-4c55-a41f-8618ccd3860a",
    #     uuid_namespace="soils segregation strengths",
    # ),
    # LUTSchema(
    #     endpoint_url="https://core.vocabs.paratoo.tern.org.au/api/lut-fauna-bird-observation-location-types",
    #     label="Bird observation location types codes",
    #     description="A collection of bird observation location types and its codes.",
    #     collection_uuid="e3a7281d-a010-430f-9a09-74cab86ac7de",
    #     uuid_namespace="bird observation location types",
    # ),
]
